### ISSUE TITLE
Removing unused Symbols from cache

### ISSUE THREAD

**Issue by AahzBrut** [Robbepop/string-interner#40]
I am planning to use string-interner in rather intense environment and it will be very convenient to have abilities:
1.  to remove Symbols from inner cache of interner by 1 and by Vec;
2.  to get all Symbols from currently cached/interned strings;

Thanks in advance, it's very useful and fast library

**Comment by Robbepop** [comment]
Hi, glad you like the library.
To answer your questions ...

1) This is kinda not possible since the `StringInterner` uses an arena-like allocation scheme. The general gist of arena allocators is: They are fast but you can only delete items in bulk. Same goes for the strings interned by the `StringInterner`.
2) This is easily possible by simply iterating over the string interner.

**Comment by AahzBrut** [comment]
1. Well, in that case deleting by Vec of symbols will be good, or if it's not good enough maybe it will be possible to add clear() to remove all currently interned strings and symbols?
2. Oh, thanks, didn't notice it first time;

**Comment by Robbepop** [comment]
I am closing this issue now since there has not been much activity lately and no further solutions have been brought up by any involved party.
