### ISSUE TITLE
Implement `Sym` for `u32` by default?

### ISSUE THREAD

**Issue by matklad** [Robbepop/string-interner#6]
Hi! It seems to me that `u32` is probably the best overall default index type for string interner: it's more compact than `usize`, is platform-independent, and it's unlikely that one would store more than u32 interned strings. 

I suggest adding `impl Sym for u32` to this crate: it's easy to roll-your own newtype wrapper around it, but it would be nice if it worked out of the box. 

Looks like this might run into coherence issues though, due to `From<usuze>` + `To<usize>` requirements? Perhaps they could be dropped? 

Totally not sure what's the best solution here, but I feel that the problem "the best u32 index requires a bit of boilerplate to write" exists :)

**Comment by koute** [comment]
An even better index would be the recently stabilized [`NonZeroU32`](https://doc.rust-lang.org/std/num/struct.NonZeroU32.html) since we can just simply guarantee that we'll have only non-zero indices, and `NonZeroU32` has an advantage of having no extra overhead when stored inside of an `Option`.

**Comment by matklad** [comment]
Ohhh, I didn't know about `NonZeroU32`, and, accidentally, this is exactly the thing I need right now for the project I want to use `stirng-interner` for as well! Thanks a bunch!

**Comment by Robbepop** [comment]
Hi,
sorry, I was too busy the last weeks for my open source projects.

@matklad You are totally right that this library is especially useful for `u32` instances and I typically use it with those. Your suggestions is thus valid. So removing the trait bounds `From<usize>` and `Into<usize>` finally has a decent rational. We should convert them into methods of `Symbol` to prevent these coherence issues.

@koute Having support for the recently stabilized `NonZeroU32` would be even better. However, I cannot guarantee at the moment that the current implementation will never return a zero index to users. Before we introduce this feature we should check that this will never happen. But besides that it would be a decent application.

Maybe specialization could improve this situation even more. So that we would only return zero indices if we aren't using `NonZeroUN` type family as index types.

**Comment by matklad** [comment]
>efore we introduce this feature we should check that this will never happen. But besides that it would be a decent application.

You can always add/subtract one internally: https://github.com/matklad/tom/blob/1bb77c735fc129e9f77053302b1ea3b570d65964/src/intern.rs#L7-L14

**Comment by Robbepop** [comment]
So true ...

The only question is if it is worth putting it into this library besides `u32`.
I think we should do it - as well as the change with the `From` and `Into` trait bounds.
What's your opinion on that matter?

**Comment by matklad** [comment]
I'd say the library should export a single default opaque type for `Symbol`, smth like

```
pub struct Sym(NonZeroU32);

impl Symbol for Sym {
   ...
}

pub type DefaultInterner = Interner<Sym>;
```

**Comment by Robbepop** [comment]
Interesting idea - I like it!
Although it would definitely break existing uses.
I will implement it later.

**Comment by matklad** [comment]
>Although it would definitely break existing uses.

Dropping `From`/`Into` is also a breaking change, so perhapse just release 0.7?

**Comment by Robbepop** [comment]
Yep :)

**Comment by Robbepop** [comment]
@matklad @koute I have implemented all your suggestions in the newest version 0.7.0: https://crates.io/crates/string-interner
Please tell me if everything matches your expectations so that I can close this issue. :)

**Comment by matklad** [comment]
0.7.0 looks perfect!
